export const ADD_HEROS = "ADD_HEROS";
export const ADD_FAVOURITE = "ADD_FAVOURITE";
export const REMOVE_FAVOURITE = "REMOVE_FAVOURITE";
export const SHOW_FAVOURITES = "SHOW_FAVOURITES";
export const ADD_HERO_TO_LIST = "ADD_HERO_TO_LIST";
export const ADD_SEARCH_RESULT = "ADD_SEARCH_RESULT";
//superheroes-details//
export const FETCH_HERO_DETAIL = "FETCH_HERO_DETAIL";
export const HERO_DETAIL_SUCCESS = "HERO_DETAIL_SUCCESS";
export const HERO_DETAIL_FAILURE = "HERO_DETAIL_FAILURE";
